/* Part of publib.

   Copyright (c) 1994-2006 Lars Wirzenius.  All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions
   are met:

   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.

   2. Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the following
      disclaimer in the documentation and/or other materials provided
      with the distribution.

   THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
   OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
   ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
   DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
   GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
.\" part of publib
.\" "@(#)publib:$Id: fname.3,v 1.1 1994/07/12 21:03:04 liw Exp $"
.\"
.TH FNAME 3 "C Programmer's Manual" Publib "C Programmer's Manual"
.SH NAME
fnbase, fndelbeg, fndelend, fndelsuf, fndir, fnhome, 
fnjoin, fnlastsuf, fnsetsuf \- filename manipulation
.SH SYNOPSIS
.nf
#include <publib.h>
.sp 1
char *\fBfnbase\fR(const char *\fIfname\fR);
void \fBfndelbeg\fR(char *\fIfname\fR);
void \fBfndelend\fR(char *\fIfname\fR);
int \fBfndelsuf\fR(char *\fIfname\fR, const char *\fIsuffix\fR);
void \fBfndir\fR(char *\fIdir\fR, const char *\fIfname\fR);
int \fBfnhome\fR(char *\fIhomedir\fR, const char *\fIusername\fR);
void \fBfnjoin\fR(char *\fIres\fR, const char *\fIf1\fR, const char *\fIf2\fR);
char *\fBfnlastsuf\fR(const char *\fIfname\fR);
size_t \fBfnsetsuf\fR(char *\fIfname\fR, const char *\fIsuf\fR, size_t \fImax\fR);
.SH DESCRIPTION
These routines manipulate POSIX-style filenames.
This manual page is still under construction.
.SH "SEE ALSO"
publib(3)
.SH AUTHOR
Lars Wirzenius (lars.wirzenius@helsinki.fi)
