.\"   Part of publib.
.\"  
.\"   Copyright (c) 1994-2006 Lars Wirzenius.  All rights reserved.
.\"  
.\"   Redistribution and use in source and binary forms, with or without
.\"   modification, are permitted provided that the following conditions
.\"   are met:
.\"  
.\"   1. Redistributions of source code must retain the above copyright
.\"      notice, this list of conditions and the following disclaimer.
.\"  
.\"   2. Redistributions in binary form must reproduce the above
.\"      copyright notice, this list of conditions and the following
.\"      disclaimer in the documentation and/or other materials provided
.\"      with the distribution.
.\"  
.\"   THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
.\"   OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\"   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\"   ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\"   DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
.\"   GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\"   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\"   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\"   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\"   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"  
.\" part of publib
.\" "@(#)publib-strutil:$Id: memoverlap.3,v 1.1 1994/02/05 17:09:24 liw Exp $"
.\"
.TH MEMOVERLAP 3 "C Programmer's Manual" Publib "C Programmer's Manual"
.SH NAME
memoverlap \- check whether two memory blocks overlap
.SH SYNOPSIS
.nf
#include <publib.h>
int \fBmemoverlap\fR(const void *\fIt\fR, size_t \fIts\fR, const void *\fIs\fR, size_t \fIss\fR);
.SH DESCRIPTION
\fImemoverlap\fR checks whether the memory blocks \fIt\fR--(\fIt+ts-1\fR)
and \fIs\fR--(\fIs+ss-1\fR) overlap.  Neither pointer argument may be
NULL, but the sizes may be 0.  The memory blocks can be arbitrary, they
do not have to be part of the same array.  Therefore, this function hides
the unportable pointer comparison that one would otherwise rely on.
.SH "RETURN VALUE"
\fImemoverlap\fR returns 0 if the blocks do not overlap, and nonzero
if they do.
.SH "SEE ALSO"
publib(3)
.SH AUTHOR
Lars Wirzenius (lars.wirzenius@helsinki.fi)
