/* Part of publib.

   Copyright (c) 1994-2006 Lars Wirzenius.  All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions
   are met:

   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.

   2. Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the following
      disclaimer in the documentation and/or other materials provided
      with the distribution.

   THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
   OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
   ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
   DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
   GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
.\" part of publib
.\" "@(#)publib-strutil:$Id: strmaxcpy.3,v 1.1.1.1 1994/02/03 17:25:29 liw Exp $"
.\"
.TH STRMAXCPY 3 "C Programmer's Manual" Publib "C Programmer's Manual"
.SH NAME
strmaxcpy \- copy at most a given number of characters of string
.SH SYNOPSIS
.nf
#include <publib.h>
char *\fBstrmaxcpy\fR(char *\fItgt\fR, const char *\fIsrc\fR, size_t \fIn\fR);
.SH DESCRIPTION
\fIstrmaxcpy\fR copies up to \fIn-1\fR characters from the beginning of
\fIsrc\fR to \fItgt\fR, then adds a '\\0'.  \fIn\fR must be at least 1.
The target string must be large enough to hold the result.
.PP
Note that unlike \fIstrncpy\fR(3), this function always terminates the
result with '\\0'.  It also doesn't fill the result with extra '\\0'
characters.
.SH "RETURN VALUE"
\fIstrmaxcpy\fR returns its first argument.
.SH EXAMPLE
To print out the first 69 characters of a string, you might do the
following (although familiarity with printf's format string might
be more useful in this case).
.sp 1
.nf
.in +5
#include <stdio.h>
#include <publib.h>

void print42(const char *string) {
	char copy[43];	/* 42 + '\\0' */

	puts(strmaxcpy(copy, string, sizeof(copy)));
}
.in -5
.SH "SEE ALSO"
publib(3), strncpy(3)
.SH AUTHOR
Lars Wirzenius (lars.wirzenius@helsinki.fi)
