.\"   Part of publib.
.\"  
.\"   Copyright (c) 1994-2006 Lars Wirzenius.  All rights reserved.
.\"  
.\"   Redistribution and use in source and binary forms, with or without
.\"   modification, are permitted provided that the following conditions
.\"   are met:
.\"  
.\"   1. Redistributions of source code must retain the above copyright
.\"      notice, this list of conditions and the following disclaimer.
.\"  
.\"   2. Redistributions in binary form must reproduce the above
.\"      copyright notice, this list of conditions and the following
.\"      disclaimer in the documentation and/or other materials provided
.\"      with the distribution.
.\"  
.\"   THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
.\"   OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\"   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\"   ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\"   DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
.\"   GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\"   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\"   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\"   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\"   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"  
.\" part of publib
.\" "@(#)publib-strutil:$Id: struntabify.3,v 1.1 1994/06/20 20:30:44 liw Exp $"
.\"
.TH STRUNTABIFY 3 "C Programmer's Manual" Publib "C Programmer's Manual"
.SH NAME
struntabify \- convert tabs to spaces
.SH SYNOPSIS
.nf
#include <publib.h>
char *\fBstruntabify\fR(char *\fIstr\fR, size_t \fItabsize\fR);
.SH DESCRIPTION
\fIstruntabify\fR will convert all tab characters ('\\t') in the string
\fIstr\fR to spaces.  Tab positions are at every \fItabsize\fR columns.
The string is supposed to be big enough to hold the conversion, which
is done in place.
.SH "RETURN VALUE"
\fIstruntabify\fR will return its first argument.
.SH "SEE ALSO"
publib(3), strtabify(3)
.SH AUTHOR
Lars Wirzenius (lars.wirzenius@helsinki.fi)
