.\" This is part of publib (big surprise :)
.\" "@(#)publib-framework:$Id: publib.3,v 1.1.1.1 1995/08/06 21:56:07 liw Exp $"
.\"
.TH PUBLIB 3
.SH NAME
publib \- introduction to publib
.SH SYNOPSIS
#include <publib.h>
.br
.SH "DESCRIPTION"
\fIpublib\fR is both a library of C functions that are useful in many
of programs, and a framework for building such a library from
components (called modules) provided by separate people.
It is an extension to the
Standard C library (as defined by the ISO/ANSI C standard 9899-1990).  To
use the functions in publib, #include <publib.h>
and link with
the libpub.a library (adding -lpub at the end of the link command
should work, if the library has been installed properly).  See the
source code and/or man page for each module for copyright restrictions
(which may be different for different modules).
.PP
The publib framework is distributed separately from the library
modules.  The framework contains no library functions at all.
Some of the currently available modules are:
.sp 1
.in +5
.nf
string and memory area manipulation
memory allocation
.\" generic data structures
I/O
.\" configuration files
comparison functions for qsort, bsearch, and others
expression evaluation
.\" dates and times
.in -5
.sp 1
.fi
More to be expected in future releases.
.SH AUTHOR
Lars Wirzenius (lars.wirzenius@helsinki.fi)
