#!/bin/sh
#  Copyright (c) 1996 Lars Wirzenius
#  Copyright (c) 2012 Antti-Juhani Kaijanaho
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#  2. Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
#  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
#  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

mode=install

while [ $# -gt 0 ]
do
    case "$1" in
        "-r")
            mode=uninstall;;
        *)
            break;;
    esac
    shift
done

rmsnd() {
    rm -f "$2"
}

find_names() {
    zcat -f "$@" |
    sed -n '/^\.SH NAME/,/^\.SH SYNOPSIS/p' |
    grep -v '^\.SH ' |
    tr '\12' ' ' |
    sed 's/ \\- .*//' |
    tr , ' ' |
    sed 's/  */ /g'
}

echoexec() {
    echo $@
    $@
}

for name in `find_names "$1"`
do
    tgt="$2/$name$3.gz"
    if [ $mode = install ] ; then
        if [ ! -f $tgt -a ! -L $tgt ]
        then
	    echoexec ln -sf `basename $1`.gz $tgt
        fi
    else
        if [ -L $tgt ] ; then
            echoexec rm $tgt
        fi
    fi
done
