.\" part of publib
.\" "@(#)publib-strutil:$Id: memisort.3,v 1.3 1996/04/08 22:27:28 liw Exp $"
.\"
.TH MEMISORT 3 "C Programmer's Manual" Publib "C Programmer's Manual"
.SH NAME
memisort \- insert new element into sorted array
.SH SYNOPSIS
.nf
#include <publib.h>

void \fBmemisort\fR(void *\fIbase\fR, size_t \fInelem\fR, size_t \fIelsize\fR, const void *\fInew\fR,
		int (*\fIcomp\fR)(const void *, const void *));
.SH DESCRIPTION
\fImemisort\fR inserts a new element into a sorted array, in the proper
place to keep the array sorted.  \fIbase\fR, \fIelsize\fR, \fInelem\fR,
and \fIcomp\fR are as for \fIqsort\fR(3), \fInew\fR is a pointer to
the new element.
.SH "SEE ALSO"
publib(3), qsort(3)
.SH AUTHOR
Lars Wirzenius (lars.wirzenius@helsinki.fi)
