.\" part of publib
.\" "@(#)publib-strutil:$Id: strend.3,v 1.1 1994/06/20 20:30:10 liw Exp $"
.\"
.TH STREND 3 "C Programmer's Manual" Publib "C Programmer's Manual"
.SH NAME
strend \- return pointer to the terminating '\\0' of a string
.SH SYNOPSIS
.nf
#include <publib.h>
char *\fBstrend\fR(const char *\fIs\fR);
.SH DESCRIPTION
\fIstrend\fR will return a pointer to the '\\0' that terminates a string.
.SH "SEE ALSO"
publib(3)
.SH AUTHOR
Lars Wirzenius (lars.wirzenius@helsinki.fi)
